# Generated by Django 3.2.13 on 2024-11-30 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleName', models.CharField(max_length=255)),
                ('vehicleType', models.CharField(max_length=100)),
                ('ownerName', models.CharField(max_length=255)),
                ('isPaid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentName', models.CharField(max_length=255)),
                ('issueType', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='vehicle.vehicle')),
            ],
        ),
    ]
